# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      - image: circleci/node:dubnium

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

      - run: yarn global add node-gyp && yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  build:
    docker:
      - image: circleci/node:dubnium

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

            - dependencies-

      - run: yarn run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build:
          requires:
            - install
