# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      - image: circleci/node:dubnium

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

      - run: yarn global add node-gyp && yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  build:
    docker:
      - image: circleci/node:dubnium

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

            - dependencies-

      - run: yarn run build

      - run: cp -r dist/ /tmp/frontend

      - persist_to_workspace:
          root: /tmp
          paths:
            - frontend

  frontend-deploy:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Deploy frontend
          command: |
            npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=/tmp/frontend

  docker-build-and-push:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag app $DOCKER_HUB_USER_ID/conduit-frontend:$CIRCLE_BUILD_NUM
            docker tag app $DOCKER_HUB_USER_ID/conduit-frontend:latest
            docker push $DOCKER_HUB_USER_ID/conduit-frontend:$CIRCLE_BUILD_NUM
            docker push $DOCKER_HUB_USER_ID/conduit-frontend:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - docker-build-and-push:
          requires:
            - install
            - build
      - frontend-deploy:
          requires:
            - install
            - build
          filters:
            branches:
              only: master
